version: '3'
services:
  node:
    container_name: pharmacy-finder-node
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - '${APP_PORT}:5173'
    entrypoint: [ 'sh', '-c', 'npm install -g npm && npm install && npm run dev' ]
